### ISSUE TITLE
backoffice/uLogs/uLogsApi/GetAvailableDates - gives 404

### ISSUE THREAD

**Issue by joco73** [wkallhof/uLogs#2]
![screenshot](https://cloud.githubusercontent.com/assets/1387023/11015700/168c87c4-8568-11e5-907c-4c69381669b3.png)

Request error: The URL returned a 404 (not found):
backoffice/uLogs/uLogsApi/GetAvailableDates 

I first tried 1.7RC and then 1.6RC, I have Umbraco 7.3, any ideas what it can be.
Installed via Nuget.

**Comment by joco73** [comment]
Okey, found the problem, the uLogs.dll did not install when using Nuget.
I collected it manually, and added to bin, and now it works.

**Comment by joco73** [comment]
My project was 4.5.1, if I changed it to 4.5.2 (4.6) it worked with nuget install.

**Comment by ghost** [comment]
I'm having the same problem as joco73. I've updated uLogs using nuget and the uLogs assembly is in my bin directory as expected. I can't see a reference to backoffice/uLogs/uLogsApi/GetAvailableDates  in the source, so I'm a bit confused.

**Comment by ghost** [comment]
Figured it out. I needed to delete the file from the folder App_Data\TEMP\ClientDependency folder and update the version number in the ClientDependency.config file.

**Comment by wkallhof** [comment]
@joco73 @codiomwnci  I'm glad you found solutions. Let me know if you continue to have issues loading this package via NuGet. I'm a bit new when it comes to creating NuGet packages that target different frameworks so if it continues to be a problem for you, I'm sure it's affecting others.
