### ISSUE TITLE
Does not pick up files with machine names

### ISSUE THREAD

**Issue by harvzor** [wkallhof/uLogs#3]
uLogs correctly picks up any log with a filename of the format `UmbracoTraceLog.txt.yyyy-mm-dd` but not of the format `UmbracoTraceLog.MACHINE_NAME.txt.yyyy-mm-dd`.

I think this new MACHINE_NAME is a late addition to log4net.

**Comment by wkallhof** [comment]
@HarveyWilliams I updated the package to look for any file that at least starts with "UmbracoTraceLog." vs requiring it to look for files that start with "UmbracoTraceLog.txt".

If any future formats cause issues, there is another option where you can specify the file name to look for via code.

Placing `uLogs.uLogsResolver.LogFileName = "UmbracoTraceLog.";` somewhere within the ApplicationStarting method for the site would tell uLogs to look for files that start with that. However, like I said, it should be updated to use that as the default check now so you shouldn't need to add that.

**Comment by harvzor** [comment]
@wkallhof Thanks. I have just tested and your fix works.
